FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.20-openshift-4.14 AS builder
WORKDIR /go/src/github.com/metal3-io/cluster-api-provider-metal3

RUN CGO_ENABLED=0 GO111MODULE=on go build -a -o bin/manager .

FROM registry.ci.openshift.org/ocp/4.14:base
COPY --from=builder /go/src/github.com/metal3-io/cluster-api-provider-metal3/bin/manager /

ENTRYPOINT ["/manager"]
