name: golangci-lint

on:
  pull_request:
    types: [ opened, edited, synchronize, reopened ]

permissions: {}

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        working-directory:
        - ""
        - test
        - api

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Calculate go version
      id: vars
      run: echo "go_version=$(make go-version)" >> $GITHUB_OUTPUT
    - name: Set up Go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      with:
        go-version: ${{ steps.vars.outputs.go_version }}
    - name: golangci-lint-${{matrix.working-directory}}
      uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6.1.1
      with:
        version: v1.60.3
        working-directory: ${{matrix.working-directory}}
        args: --timeout=15m
